name: workshop_manager
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  awesome_notifications: ^0.10.0
  bloc: ^8.1.4
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  device_info_plus: ^10.1.2
  dio: ^5.7.0
  dotted_border: ^2.1.0
  equatable: ^2.0.5
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.3
  flutter:
    sdk: flutter
  flutter_advanced_switch: ^3.1.0
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  flutter_otp_text_field: ^1.2.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.10+1
  fluttertoast: ^8.2.8
  geocoding: ^3.0.0
  geolocator: ^13.0.1
  get_it: ^8.0.0
  go_router: ^14.2.7
  google_maps_flutter: ^2.9.0
  image_picker: ^1.1.2
  intl: ^0.19.0
  intl_utils: ^2.8.7
  local_auth: ^2.3.0
  location: ^7.0.0
  meta: ^1.15.0
  mobile_scanner: ^6.0.0
  permission_handler: ^11.3.1
  qr_code_scanner: ^1.0.1
  shared_preferences: ^2.3.2
dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/images/vectors/
    - assets/images/gifs/
  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Black.ttf
        - asset: assets/fonts/Tajawal-Bold.ttf
        - asset: assets/fonts/Tajawal-ExtraBold.ttf
        - asset: assets/fonts/Tajawal-ExtraLight.ttf
        - asset: assets/fonts/Tajawal-Light.ttf
        - asset: assets/fonts/Tajawal-Medium.ttf
        - asset: assets/fonts/Tajawal-Regular.ttf
flutter_intl:
  enabled: true
