// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChx7FzTPZtkwkHKmUzE_zMCdv_HtKdtOw',
    appId: '1:305318370335:web:1c3dbaee4320830d3c092a',
    messagingSenderId: '305318370335',
    projectId: 'appify-de367',
    authDomain: 'appify-de367.firebaseapp.com',
    storageBucket: 'appify-de367.appspot.com',
    measurementId: 'G-9RR74T69V8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEfiRcMNGE0J37MlsEuQChADU0cXK77wA',
    appId: '1:305318370335:android:9a14a2db981c9e243c092a',
    messagingSenderId: '305318370335',
    projectId: 'appify-de367',
    storageBucket: 'appify-de367.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApcwDc-h5tdmHo5AialX-Nn8ipn0n80QM',
    appId: '1:305318370335:ios:ff6959d53578439c3c092a',
    messagingSenderId: '305318370335',
    projectId: 'appify-de367',
    storageBucket: 'appify-de367.appspot.com',
    iosBundleId: 'com.example.workshopManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApcwDc-h5tdmHo5AialX-Nn8ipn0n80QM',
    appId: '1:305318370335:ios:ff6959d53578439c3c092a',
    messagingSenderId: '305318370335',
    projectId: 'appify-de367',
    storageBucket: 'appify-de367.appspot.com',
    iosBundleId: 'com.example.workshopManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChx7FzTPZtkwkHKmUzE_zMCdv_HtKdtOw',
    appId: '1:305318370335:web:971f650b21992df23c092a',
    messagingSenderId: '305318370335',
    projectId: 'appify-de367',
    authDomain: 'appify-de367.firebaseapp.com',
    storageBucket: 'appify-de367.appspot.com',
    measurementId: 'G-TNP7K0938T',
  );

}